{% set name = "metaflow-stubs" %}
{% set version = "2.11.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2d97ceb4c22e7cb84ff5724efa9e826598c3572237cf68814d5794adf7afa8cb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  commands:
    - test -d ${SP_DIR}/metaflow-stubs  # [unix]
    - test -f ${SP_DIR}/metaflow-stubs/__init__.pyi  # [unix]
    - if exist %SP_DIR%\metaflow-stubs\__init__.pyi (exit 0) else (exit 1)  # [win]

about:
  home: https://metaflow.org
  summary: 'Metaflow Stubs: Stubs for the metaflow package'
  doc_url: https://docs.metaflow.org
  dev_url: https://github.com/Netflix/metaflow
  license: Apache-2.0
  license_file: LICENSE
  license_family: APACHE

extra:
  recipe-maintainers:
    - madhur-ob
    - saikonen
    - savingoyal
